name: AppMap Analysis

on: [ push ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # Install AppMap library and tools
      - name: Enable appmap gem update
        run: bundle config unset deployment      
      - name: Install AppMap tools
        uses: getappmap/install-action@v1.0
        with:
          project-type: bundler

      - name: Rails test setup
        run: ./bin/rails db:migrate

      - name: Run tests
        run: ./bin/rails test

      - name: Archive AppMaps
        uses: getappmap/archive-action@v1-pre.13
        with:
          revision: 3ce97866eb1b59bff68fbc67845513209c67a7c4
