name: AppMap Analysis

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  DISABLE_SPRING: 'true'

jobs:
  appmap-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare bundle for AppMap installation
        run: bundle config unset deployment
      - name: Install AppMap tools
        uses: getappmap/install-action@v1.0
        with:
          tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-faster-v1.0-pre.2/appmap-linux-x64
          project-type: bundler

      - name: Rails test setup
        run: ./bin/rails db:migrate
      - name: Run tests
        run: ./bin/rails test

      - name: Archive AppMaps
        if: github.event_name != 'pull_request'
        uses: getappmap/archive-action@feat/thread-count
        with:
          verbose: true

      - name: Analyze AppMaps
        if: (success() || failure()) && github.event_name == 'pull_request'
        uses: getappmap/analyze-action@feat/thread-count
        with:
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true
