name: Run Tests and Archive AppMaps

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  APPMAP_TELEMETRY_DISABLED: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare bundle for AppMap installation
        run: bundle config unset deployment
      - name: Install AppMap tools
        uses: getappmap/install-action@v1-pre.9
        with:
          project-type: bundler
          verbose: true
      - name: Rails test setup
        run: ./bin/rails db:migrate
      - name: Run tests
        run: ./bin/rails test || true
      - name: Archive AppMaps
        uses: getappmap/archive-action@v1-pre.13
        with:
          revision: $GITHUB_SHA
          verbose: true
