name: appmap-analysis

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Rails test setup
        run: ./bin/rails db:migrate
      - name: Run tests
        run: ./bin/rails test
      
      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  appmap-analysis:
    if: always()
    analyze:
    # If your organization has 4-core runners available, you should change this line to use
    # those runners. 4 cores offers the best performance for AppMap analysis.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          directory: .
          install-appmap-library: false

      - name: Restore AppMaps
        uses: actions/cache/restore@v3
        with:
          path: ${{ inputs.directory }}/${{ steps.install-appmap.outputs.appmap-dir }}
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

      - name: Archive AppMaps
        if: github.event_name != 'pull_request'
        uses: getappmap/archive-action@v1
        with:
          directory: .

      - name: Analyze AppMaps
        uses: getappmap/analyze-action@v1
        if: github.event_name == 'pull_request'
        with:
          archive-retention-days: 90
          directory: .
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}