name: AppMap Analysis

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  DISABLE_SPRING: 'true'

jobs:
  appmap-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare bundle for AppMap installation
        run: bundle config unset deployment
      - name: Install AppMap tools
        uses: getappmap/install-action@v1-pre.9
        with:
          project-type: bundler
      - name: Rails test setup
        run: ./bin/rails db:migrate
      - name: Run tests
        run: ./bin/rails test
      - name: Analyze AppMaps
        if: (success() || failure()) && github.event_name == 'pull_request'
        uses: getappmap/analyze-action@v1-pre.13
        with:
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: PR Comment AppMap Report
        if: (success() || failure()) && github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ".appmap/change-report/${{ github.event.pull_request.base.sha }}-${{ github.event.pull_request.head.sha }}/report.md"
          comment_tag: appmap # This lets AppMap update the initial comment with a new report.
      - name: Archive AppMaps
        if: (success() || failure()) && github.event_name == 'push'
        uses: getappmap/archive-action@v1-pre.13
        