name: Publish OpenAPI to Smartbear

on:
  push:
    branches:
      - smartbear-integration

env:
  DISABLE_SPRING: 'true'
  SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}

jobs:
  publish-openapi-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install SmartBear CLI
        run: npm i -g swaggerhub-cli 

      - name: Prepare bundle for AppMap installation
        run: bundle config unset deployment
      - name: Install AppMap tools
        uses: getappmap/install-action@v1
        with:
          project-type: bundler

      - name: Rails test setup
        run: ./bin/rails db:migrate
      - name: Run tests
        run: ./bin/rails test

      - name: Set API Version Number
        run: ${{env.OPENAPI_VERSION}}=$(cat openapi-version) 

      - name: Generate OpenAPI with AppMap
        run: appmap openapi --output-file openapi.yml --openapi-title rails_tutorial_sample_app_7th_ed --openapi-version ${OPENAPI_VERSION}

      - name: Publish API to SmartBear
        run: swaggerhub api:create AppMap/rails_tutorial_sample_app_7th_ed --file openapi.yml

      - name: Set Latest API Default
        run: swaggerhub api:setdefault AppMap/rails_tutorial_sample_app_7th_ed/${OPENAPI_VERSION}
        